function generateDriveTreeHTML() {
    const rootFolder = DriveApp.getRootFolder();
    let htmlContent = `
  <!DOCTYPE html>
  <html>
  <head>
    <title>Google Drive Visual Map</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif; padding: 20px; background-color: #f8f9fa; }
      ul { list-style-type: none; padding-left: 20px; }
      .folder { cursor: pointer; font-weight: bold; color: #1a73e8; margin: 5px 0; user-select: none; }
      .folder::before { content: "📁 "; }
      .file { margin: 5px 0; color: #5f6368; }
      .file::before { content: "📄 "; }
      .nested { display: none; }
      .active { display: block; }
    </style>
  </head>
  <body>
    <h2>My Google Drive Map</h2>
    <p><i>Note: Click on folders to expand/collapse them.</i></p>
    <ul>
  `;

    // Helper function to recursively build the tree
    // Note: Deep or massive drives may hit Google's 6-minute execution limit.
    function buildTree(folder, depth) {
        if (depth > 4) return; // Limits depth to prevent timeouts on large drives

        let subFolders = folder.getFolders();
        let files = folder.getFiles();

        // Process subfolders
        while (subFolders.hasNext()) {
            let currentFolder = subFolders.next();
            htmlContent += `<li><div class="folder" onclick="this.parentElement.querySelector('.nested').classList.toggle('active')">${currentFolder.getName()}</div><ul class="nested">`;
            buildTree(currentFolder, depth + 1);
            htmlContent += `</ul></li>`;
        }

        // Process files
        while (files.hasNext()) {
            let currentFile = files.next();
            htmlContent += `<li class="file">${currentFile.getName()}</li>`;
        }
    }

    buildTree(rootFolder, 0);

    htmlContent += `
    </ul>
  </body>
  </html>
  `;

    // Step 3: Create the HTML file in your Drive
    const newFile = rootFolder.createFile('Drive_Visual_Map.html', htmlContent, MimeType.HTML);
    Logger.log('File created successfully! Check your My Drive root folder for: ' + newFile.getName());
}
/*No, the HTML file generated by that script is a **static snapshot**. It captures the state of your Google Drive at the exact moment you run the script. If you add, delete, or rename files afterward, those changes will not appear in that specific HTML file.
To see an updated version, you would need to ** run the script again ** to generate a fresh file.
Why it isn't "Live"
Standard HTML files are just text documents.Once the script writes the names of your folders and files into that file, the connection to your live Drive is severed.For a file to update in real - time, it would require a "Live Web App" setup.

### How to make it(nearly) Real - Time
If you want the visual map to stay current without manual effort, you can set up an ** Automated Trigger **:

1.  In the Google Apps Script editor, click the ** Triggers ** icon(the clock shape on the left sidebar).
2.  Click ** + Add Trigger ** in the bottom right.
3.  Set "Select event source" to ** Time - driven **.
4.  Set "Select type of time based trigger" to ** Day timer ** (e.g., every midnight) or ** Hour timer **.
5.  Click ** Save **.

With this setting, the script will automatically overwrite the HTML file with your latest Drive structure on the schedule you choose.



### A Truly "Live" Alternative
If you need to see changes the second they happen, you can modify the script to ** "Deploy as Web App" **:
1.  In the script editor, click ** Deploy ** > ** New Deployment **.
2.  Select ** Web App **.
3.  Set "Execute as" to ** Me ** and "Who has access" to ** Only myself **.
4.  Click ** Deploy **.

This will give you a ** URL **.Every time you visit that URL in your browser, the script runs instantly and builds a visual map of your Drive's current state.

Would you like the modified code to turn this into a live Web App URL instead ?*/


function generateInteractiveDriveMap() {
  const rootFolder = DriveApp.getRootFolder();
  let driveData = [];

  // 1. Extract Data into a structured array
  function scanFolder(folder, currentPath, depth) {
    if (depth > 4) return; // Prevent timeouts

    let subFolders = folder.getFolders();
    while (subFolders.hasNext()) {
      let f = subFolders.next();
      driveData.push({
        name: f.getName(),
        type: 'Folder',
        path: currentPath,
        url: f.getUrl()
      });
      scanFolder(f, currentPath + f.getName() + '/', depth + 1);
    }

    let files = folder.getFiles();
    while (files.hasNext()) {
      let f = files.next();
      driveData.push({
        name: f.getName(),
        type: 'File',
        path: currentPath,
        url: f.getUrl()
      });
    }
  }

  scanFolder(rootFolder, '/', 0);

  // 2. Inject data into an interactive HTML template
  const htmlContent = `
  <!DOCTYPE html>
  <html>
  <head>
    <title>Interactive Drive Map</title>
    <style>
      body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; padding: 20px; background: #f8f9fa; color: #202124; }
      .controls { display: flex; gap: 15px; margin-bottom: 20px; }
      input, select { padding: 8px 12px; border: 1px solid #dadce0; border-radius: 4px; font-size: 14px; outline: none; }
      input:focus, select:focus { border-color: #1a73e8; }
      input[type="text"] { flex-grow: 1; }
      table { width: 100%; border-collapse: collapse; background: white; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
      th, td { padding: 12px 15px; text-align: left; border-bottom: 1px solid #e8eaed; }
      th { background: #f1f3f4; cursor: pointer; user-select: none; font-weight: 600; }
      th:hover { background: #e8eaed; }
      tr:hover { background: #f8f9fa; }
      a { color: #1a73e8; text-decoration: none; }
      a:hover { text-decoration: underline; }
      .folder-icon::before { content: "📁 "; }
      .file-icon::before { content: "📄 "; }
    </style>
  </head>
  <body>
    <h2>Interactive Drive Map</h2>
    
    <div class="controls">
      <input type="text" id="searchInput" placeholder="Find files or folders (Press '/' to focus)..." autofocus>
      <select id="typeFilter">
        <option value="All">All Types</option>
        <option value="Folder">Folders Only</option>
        <option value="File">Files Only</option>
      </select>
    </div>

    <table>
      <thead>
        <tr>
          <th onclick="handleSort('name')">Name ↕</th>
          <th onclick="handleSort('type')">Type ↕</th>
          <th onclick="handleSort('path')">Path ↕</th>
        </tr>
      </thead>
      <tbody id="tableBody"></tbody>
    </table>

    <script>
      // The raw structural data injected from Google Apps Script
      const data = ${JSON.stringify(driveData)};
      
      let currentData = [...data];
      let sortCol = 'name';
      let sortAsc = true;

      const tableBody = document.getElementById('tableBody');
      const searchInput = document.getElementById('searchInput');
      const typeFilter = document.getElementById('typeFilter');

      // Core render function
      function renderTable(dataset) {
        tableBody.innerHTML = '';
        dataset.forEach(item => {
          const iconClass = item.type === 'Folder' ? 'folder-icon' : 'file-icon';
          const row = \`<tr>
            <td class="\${iconClass}"><a href="\${item.url}" target="_blank">\${item.name}</a></td>
            <td>\${item.type}</td>
            <td style="color: #5f6368; font-size: 0.9em;">\${item.path}</td>
          </tr>\`;
          tableBody.innerHTML += row;
        });
      }

      // Filter and Find logic
      function applyFilters() {
        const query = searchInput.value.toLowerCase();
        const filterValue = typeFilter.value;
        
        currentData = data.filter(item => {
          const matchesSearch = item.name.toLowerCase().includes(query) || item.path.toLowerCase().includes(query);
          const matchesType = filterValue === 'All' || item.type === filterValue;
          return matchesSearch && matchesType;
        });
        
        sortData(sortCol, sortAsc); // Maintain sort state after filtering
      }

      // Sort logic
      function sortData(column, asc) {
        currentData.sort((a, b) => {
          let valA = a[column].toLowerCase();
          let valB = b[column].toLowerCase();
          if (valA < valB) return asc ? -1 : 1;
          if (valA > valB) return asc ? 1 : -1;
          return 0;
        });
        renderTable(currentData);
      }

      function handleSort(column) {
        if (sortCol === column) {
          sortAsc = !sortAsc; // Toggle direction
        } else {
          sortCol = column;
          sortAsc = true;
        }
        sortData(sortCol, sortAsc);
      }

      // Event Listeners
      searchInput.addEventListener('input', applyFilters);
      typeFilter.addEventListener('change', applyFilters);
      
      // Keyboard shortcut: Press '/' to quickly focus the search bar
      document.addEventListener('keydown', (e) => {
        if (e.key === '/' && document.activeElement !== searchInput) {
          e.preventDefault();
          searchInput.focus();
        }
      });

      // Initial Render
      sortData('name', true);
    </script>
  </body>
  </html>
  `;

  // 3. Create the file
  const newFile = rootFolder.createFile('Interactive_Drive_Map.html', htmlContent, MimeType.HTML);
  Logger.log('File created successfully: ' + newFile.getName());
}